import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import NavigationBar from '@/components/NavigationBar';

//const inter = Inter({ subsets: ['latin'] })
const montserratFont = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});

export const metadata = {
  title: 'R & S Constructions | General Contractor & Home Remodeling',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserratFont.className} font-sans w-full min-h-screen bg-ivory`}>
        <div className='max-w-[1920px] mx-auto'>
          <NavigationBar />
          {children}
        </div>
      </body>
    </html>
  )
}
